### ISSUE TITLE
esp_private/esp_ldo.h doesn't exist

### ISSUE THREAD

**Issue by rightcornerengineering** [espzav/Simple-LVGL-Player#1]
I am getting the following error when trying to build in esp-idf 5.3.
```
../components/esp32_p4_function_ev_board/esp32_p4_function_ev_board.c:15:10: fatal error: esp_private/esp_ldo.h: No such file or directory
   15 | #include "esp_private/esp_ldo.h"
```

**Comment by espzav** [comment]
Hi @rightcornerengineering,
Thank you for report this issue. I fixed it in latest commit. But there is still issue with initialization of SD card. Please wait for this PR: https://github.com/espressif/esp-bsp/pull/366

**Comment by rightcornerengineering** [comment]
> Hi @rightcornerengineering, Thank you for report this issue. I fixed it in latest commit. But there is still issue with initialization of SD card. Please wait for this PR: [espressif/esp-bsp#366](https://github.com/espressif/esp-bsp/pull/366)

Thank you @espzav for the quick fix.
I have esp32-p4-ev-board (https://ko.aliexpress.com/item/1005007259059322.html?spm=a2g0o.order_list.order_list_main.11.55e0140fxr6kh5&gatewayAdapt=glo2kor) in hands and is this repo going to be fully compatible with the esp32-p4 eval board?

**Comment by rightcornerengineering** [comment]
@espzav It would be also great if there's more information of target device and esp-idf version, etc. in README. Thank you.

**Comment by espzav** [comment]
@rightcornerengineering The project is using this BSP: https://github.com/espressif/esp-bsp/tree/master/bsp/esp32_p4_function_ev_board it is fully compatible with latest Function Evaluation board and we are still updating it. There will be HDMI support too in future (I hope :-) ).

I updated readme of this project too. There is selection between two boards (or two LCD connected). 

This project was only like demo, but I would like to add support for more features and  more BSP boards too.

**Comment by rightcornerengineering** [comment]
@espzav , Thank you for the explanation.
README looks more details now :-)

Feel free to close this issue since you have fixed the reported issue. Thank you.

**Comment by espzav** [comment]
Initialization of SD card was fixed. Closing.
